enableGlobalCache: false

httpProxy: "http://localhost:8889"

nodeLinker: node-modules

npmRegistries:
  //gitlab.com/api/v4/projects/30727907/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: o4KgpPEKyPbbCR-yQVhh

npmScopes:
  avidkit:
    npmPublishRegistry: "https://gitlab.com/api/v4/projects/30727907/packages/npm/"
    npmRegistryServer: "https://gitlab.com/api/v4/projects/30727907/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.3.cjs
